
import java.awt.Color;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Haro
 */
public class ViewBotonesListas extends javax.swing.JFrame {

    /**
     * Creates new form ViewBotonesListas
     */
    public ViewBotonesListas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelColores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        cboColores = new javax.swing.JComboBox<>();
        cboRojo = new javax.swing.JComboBox<>();
        cboAzul = new javax.swing.JComboBox<>();
        cboVerde = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelColores.setBackground(java.awt.SystemColor.textHighlight);
        panelColores.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                panelColoresPropertyChange(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        cboColores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleciona opción", "Rojo", "Verde", "Azul", "Amarillo" }));
        cboColores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboColoresItemStateChanged(evt);
            }
        });

        cboRojo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opción", "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200", "210", "220", "230", "240", "255", "300" }));
        cboRojo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboRojoItemStateChanged(evt);
            }
        });

        cboAzul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opción", "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200", "210", "220", "230", "240", "255", "300" }));
        cboAzul.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboAzulItemStateChanged(evt);
            }
        });

        cboVerde.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opción", "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200", "210", "220", "230", "240", "255", "300" }));
        cboVerde.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboVerdeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelColoresLayout = new javax.swing.GroupLayout(panelColores);
        panelColores.setLayout(panelColoresLayout);
        panelColoresLayout.setHorizontalGroup(
            panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelColoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelColoresLayout.setVerticalGroup(
            panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColoresLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelColoresPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_panelColoresPropertyChange
       
    }//GEN-LAST:event_panelColoresPropertyChange

    private void cboColoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboColoresItemStateChanged
         String color = cboColores.getSelectedItem().toString();
        System.out.println("Color"+color);
        switch(color.toLowerCase()){
            case "rojo":
        panelColores.setBackground(Color.red);
        break;
            case "verde":
        panelColores.setBackground(Color.green);
        break;
        case "azul":
        panelColores.setBackground(Color.blue);
        break;
        case "amarillo":
        panelColores.setBackground(Color.yellow);
        break;
        }
        
        
    }//GEN-LAST:event_cboColoresItemStateChanged

    private void cboRojoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboRojoItemStateChanged
         int color1 =Integer.parseInt( cboRojo.getSelectedItem().toString());
         int color2 =Integer.parseInt( cboAzul.getSelectedItem().toString());
         int color3 =Integer.parseInt( cboVerde.getSelectedItem().toString());   
          panelColores.setBackground(new Color(color1,color2,color3));
    }//GEN-LAST:event_cboRojoItemStateChanged

    private void cboAzulItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboAzulItemStateChanged
        int color1 =Integer.parseInt( cboRojo.getSelectedItem().toString());
         int color2 =Integer.parseInt( cboAzul.getSelectedItem().toString());
         int color3 =Integer.parseInt( cboVerde.getSelectedItem().toString());   
          panelColores.setBackground(new Color(color1,color2,color3));
    }//GEN-LAST:event_cboAzulItemStateChanged

    private void cboVerdeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboVerdeItemStateChanged
        int color1 =Integer.parseInt( cboRojo.getSelectedItem().toString());
         int color2 =Integer.parseInt( cboAzul.getSelectedItem().toString());
         int color3 =Integer.parseInt( cboVerde.getSelectedItem().toString());   
          panelColores.setBackground(new Color(color1,color2,color3));
    }//GEN-LAST:event_cboVerdeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBotonesListas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboAzul;
    private javax.swing.JComboBox<String> cboColores;
    private javax.swing.JComboBox<String> cboRojo;
    private javax.swing.JComboBox<String> cboVerde;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelColores;
    // End of variables declaration//GEN-END:variables
}
